env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - standard

parser: babel-eslint

parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

plugins:
  - standard

rules:
  no-console:
    - warn
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  import/no-unresolved: 1
  import/named: 1
