env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'standard'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
parser: babel-eslint
plugins:
  - standard
rules:
  no-console:
    - warn
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  import/no-unresolved: 1
  import/named: 1
